language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get update
  - sudo apt-get install php5-dev
  - git submodule init
  - git submodule update

script:
  - make clean
  - cd lib/libsass && make && cd ../..
  - phpize
  - ./configure
  - make

after_success:
  - make test

notifications:
    on_success: never
    on_failure: never

os:
  - linux
  - osx
