language: php
php:
  - 5.4
  - 5.5
  - 5.6

global:
    # Configure the .phpt tests to be Travis friendly
    - REPORT_EXIT_STATUS=1
    - TEST_PHP_ARGS="-q -s output.txt -g XFAIL,FAIL,BORK,WARN,LEAK,SKIP -x --show-diff"

compiler:
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get update -qq
  - sudo apt-get install -y php5-dev
  - sudo apt-get install -y apache2
  - sudo a2enmod actions
  - sudo a2enmod rewrite
  - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
  - echo "$(curl -fsSL https://gist.github.com/roderik/16d751c979fdeb5a14e3/raw/gistfile1.txt)" | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
  - echo "$(curl -fsSL https://gist.github.com/roderik/2eb301570ed4a1f4c33d/raw/gistfile1.txt)" | sed -e "s,PATH,`pwd`/web,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  - sudo service apache2 restart
  - git submodule init
  - git submodule update
  - make clean
  - cd lib/libsass && make && cd ../..
  - phpize
  - ./configure
  - make
  - echo "extension = sass.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - make test 
  - ./bin/phpunit

notifications:
    on_success: never
    on_failure: never

os:
  - linux
