language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

allow_failures:
    - php: nightly
  fast_finish: true

addons:
  apt:
    packages:
      - php-5dev
      - valgrind

env:
  global:
    # Configure the .phpt tests to be Travis friendly
    - REPORT_EXIT_STATUS=1
    - TEST_PHP_ARGS="-q -s output.txt -g XFAIL,FAIL,BORK,WARN,LEAK,SKIP -x --show-diff"
    # Add the pip installation folder to the PATH, until https://github.com/travis-ci/travis-ci/issues/3563 is fixed
    - PATH=$HOME/.local/bin:$PATH

compiler:
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - composer require satooshi/php-coveralls --dev
  - git submodule init
  - git submodule update

before_script:
  - travis_retry composer self-update
  - composer config discard-changes true

script:
  - make clean
  - cd lib/libsass && make && cd ../..
  - phpize
  - ./configure
  - make
  - echo "extension = sass.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${TRAVIS_BUILD_DIR}/modules"
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml
  - make test

notifications:
    on_success: never
    on_failure: never

os:
  - linux

matrix:
  fast_finish: true
