platform:
  - x64
  - x86

configuration:
  - Debug
  - Release

install:
  - cd C:\projects\sassphp
  - git submodule init
  - git submodule update
  - cinst php5-dev
  - SET PATH=C:\php\;%PATH%
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - cd C:\php-src\
  - buildconf.bat --add-modules-dir=C:\projects\sassphp
  - configure.bat --disable-all --enable-cli --enable-sass
  - nmake php_sass.dll

build: OFF

test: OFF

test_script: OFF

deploy: OFF